### ISSUE TITLE
coffee-react (cjsx) support

### ISSUE THREAD

**Issue by spudly** [benbria/coffee-coverage#52]
I would love to have support for [coffee-react](https://github.com/jsdf/coffee-react) (.cjsx) files. I may even be willing to submit a pull request if someone provide some insight into how coffee-coverage works.

**Comment by jwalton** [comment]
I would welcome a PR for sure.

The 5 mile high view of coffee-coverage is; first we use [coffee-script to parse the input and generate an AST](https://github.com/benbria/coffee-coverage/blob/master/src/coffeeCoverage.coffee#L310).  Then we visit every node in the AST with an [instrumentor](https://github.com/benbria/coffee-coverage/tree/master/src/instrumentors) which, generally, adds some extra nodes into the resulting coffee-script.  Finally we [compile the resulting AST](https://github.com/benbria/coffee-coverage/blob/master/src/coffeeCoverage.coffee#L341) out into JavaScript.

All the information about where a particular fragment of source came from is based on the [`locationData`](https://github.com/jashkenas/coffeescript/blob/master/src/helpers.coffee#L98) found in the coffee-script node.

**Comment by GeoffreyBooth** [comment]
CoffeeScript 2 includes support for CSX/JSX: http://coffeescript.org/v2/#jsx

Such a file currently chokes `coffee-coverage`:
```
~/coffeescript/node_modules/coffee-coverage/lib/coffeeCoverage.js:279
      throw new CoverageError(“Could not parse “ + fileName + “: “ + err.stack);
      ^
CoverageError: Could not parse ~/coffeescript/documentation/examples/jsx.coffee:
[stdin]:9:4: error: missing / (unclosed regex)
  </aside>
   ^
    at Object.exports._runInstrumentor (/Volumes/Geoffrey/Sites/coffeescript/node_modules/coffee-coverage/lib/coffeeCoverage.js:279:13)
    at CoverageInstrumentor.exports.CoverageInstrumentor.CoverageInstrumentor.instrumentCoffee (/Volumes/Geoffrey/Sites/coffeescript/node_modules/coffee-coverage/lib/coffeeCoverage.js:237:24)
```
