### ISSUE TITLE
CoverageError when trying coffee-coverage-loader.js

### ISSUE THREAD

**Issue by dynnamitt** [benbria/coffee-coverage#76]
node v4.2.6

when

>     /node_modules/.bin/mocha -R spec --compilers coffee:coffee-script/register --require ./coffee-coverage-loader

I get

> (node) child_process: options.customFds option is deprecated. Use options.stdio instead.
> 
> /home/kfm/code/ds3g/readin/node_modules/coffee-coverage/lib/coffeeCoverage.js:279
>       throw new CoverageError("Could not parse " + fileName + ": " + err.stack);
>       ^
> CoverageError: Could not parse /home/kfm/code/ds3g/readin/node_modules/halbert/node_modules/browserify/node_modules/browser-resolve/test/fixtures-coffee/foo.coffee: SyntaxError: unexpected //
>   at Object.exports._runInstrumentor (/home/kfm/code/ds3g/readin/node_modules/coffee-coverage/lib/coffeeCoverage.js:279:13)
>   at CoverageInstrumentor.exports.CoverageInstrumentor.CoverageInstrumentor.instrumentCoffee (/home/kfm/code/ds3g/readin/node_modules/coffee-coverage/lib/coffeeCoverage.js:237:24)
>   at CoverageInstrumentor.exports.CoverageInstrumentor.CoverageInstrumentor.instrumentFile (/home/kfm/code/ds3g/readin/node_modules/coffee-coverage/lib/coffeeCoverage.js:219:21)
>   at CoverageInstrumentor.exports.CoverageInstrumentor.CoverageInstrumentor.instrumentDirectory (/home/kfm/code/ds3g/readin/node_modules/coffee-coverage/lib/coffeeCoverage.js:196:27)
>   at CoverageInstrumentor.exports.CoverageInstrumentor.CoverageInstrumentor.instrumentDirectory (/home/kfm/code/ds3g/readin/node_modules/coffee-coverage/lib/coffeeCoverage.js:182:23)
>

**Comment by dynnamitt** [comment]
coffee-coverage-loader.js is copy-paste from sample...

**Comment by dynnamitt** [comment]
FIX;

changed exclude into

      exclude: ['**/test', '**/node_modules', '**/.git'],

**Comment by jwalton** [comment]
Hmm... Sounds like we broke something when we added glob support in 1.0.0.

**Comment by jwalton** [comment]
Ok, this is weird though, because I just tried upgrading to latest coffee-coverage in [amqp-connnection-manager](https://github.com/benbria/node-amqp-connection-manager), and it runs fine, even though it's using [the defaults](https://github.com/benbria/coffee-coverage/blob/master/register-istanbul.js#L12).  Even if I `npm install halbert`, so I have this exact same file locally...

Do you have an example project that reproduces this?  Also, when you're running mocha, you're running it a `./node_modules/.bin/mocha`?  Not trying to run it from another folder?

Thanks!

**Comment by dynnamitt** [comment]
yes,
My halberd ver tag is ^0.1.0 if it helps.

Im fine as long as I use this file

> var COV_DIR = 'coverage';
> var COV_DEST = 'coverage-coffee.json';
> 
> var path = require('path');
> var coffeeCoverage = require('coffee-coverage');
> var projectRoot = __dirname;
> var coverageVar = coffeeCoverage.findIstanbulVariable();
> // Only write a coverage report if we're not running inside of Istanbul.
> 
> 
> /* jshint ignore:start */
> var writeOnExit = (coverageVar == null) ? (projectRoot + '/' + COV_DIR + '/' + COV_DEST) : null;
> /* jshint ignore:end */
> 
> // console.warn ("coverageVar:", coverageVar);
> // console.warn ("writeOnExit:", writeOnExit);
> // console.warn ("pRoot:", projectRoot);
> 
> coffeeCoverage.register({
>   instrumentor: 'istanbul',
>   basePath: projectRoot,
>   exclude: ['test', 'node_modules', '.git', 'features', '_*' ,'coverage'],
>   coverageVar: coverageVar,
>   writeOnExit: writeOnExit,
>   initAll: true
> });
